### ISSUE TITLE
Spirit App not detecting groups with data-spirit-id for gatsby react app

### ISSUE THREAD

**Issue by Gervwyk** [spirit/spirit#23] opened 2018-01-04 22:52 UTC
I'm running a simple gatsby react app and rendering a component with `<div data-spirit-id="landscape">` which in react 16 does render to dom. Thus the html element with `data-spirit-id` exists in the dom when I click the chrome app to start editing the animation, yet the Spirit app does not detect these groups with `data-spirit-id` defined. 
However, if I click to select a element and then create an animation it does work when creating animation - have not yet tested in production.

**Spirit version:**
version 0.13.2 

Nice app btw.

**Comment by inlet** [comment] 2018-01-05 06:49
Could you please be more specific how to reproduce this? Maybe add some code, thanks!

**Comment by Gervwyk** [comment] 2018-01-05 07:42
Currently running a default gatsby app:
package.json
```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "",
  "dependencies": {
    "antd": "^3.1.0",
    "gatsby": "^1.9.145",
    "gatsby-link": "^1.6.32",
    "gatsby-plugin-less": "^1.0.8",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "spiritjs": "^2.2.4"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.9.2"
  }
}
```
and  on my main index page I have `src/pages/index.js`:

```
import React from 'react';
import Link from 'gatsby-link';
import spirit from 'spiritjs';

const IndexPage = () => (
  <div data-spirit-id="landscape">
    <h1>MRM Support</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <Link to="/page-2/">Page 2</Link>
    <div data-spirit-id="landscape1">
      <div>hello text</div>
    </div>
  </div>
);
export default IndexPage;
```
The code renders in dom as:
![screen shot 2018-01-05 at 9 40 45 am](https://user-images.githubusercontent.com/7165064/34599765-a6a8803a-f1fc-11e7-99d2-d72fd813d79d.png)

For more info on gatsby see:
https://www.gatsbyjs.org/docs/

**Comment by inlet** [comment] 2018-01-05 07:52
Seems to be fine, what exactly doesn’t work?

**Comment by Gervwyk** [comment] 2018-01-05 07:55
When this page is open and clicking the chrome extention, the app does not detect the groups, and I have to select XPath groups, then it works.

**Comment by inlet** [comment] 2018-01-05 07:59
Do you have an example where you load/create animation groups? Can’t find it in your code.

Or do you mean you cannot select the elements during create group?

Sorry it’s not clear to me

**Comment by Gervwyk** [comment] 2018-01-05 08:02
so after clicking the chrome app. should the Spirit app pick up the `data-spirit-id` elements on this page?
![screen shot 2018-01-05 at 10 01 27 am](https://user-images.githubusercontent.com/7165064/34600294-6b07b070-f1ff-11e7-9146-67ca34c13cdc.png)
Or do I need to add some code before it will detect the groups?

**Comment by inlet** [comment] 2018-01-05 08:06
First you’ll need to create a group. Select the elements and give it a name..

https://docs.spiritapp.io/app_create_groups.html

Once the group is created it will be listed there and you can animate it.. once satisfied you can export the animation and use the Spirit runtime to play the animation:

https://docs.spiritapp.io/gsap_runtime_simple.html

Please let me know if you encounter any problems

**Comment by Gervwyk** [comment] 2018-01-05 08:31
Yes. but the app is not detecting my `data-spirit-id` groups, so I have to use XPaths. then it works. Should the app automatically detect the  `data-spirit-id` groups on the page?

**Comment by Gervwyk** [comment] 2018-01-05 08:37
Ok. Got it working correctly now.

**Comment by inlet** [comment] 2018-01-05 09:08
Glad it worked out, closing this issue now 😉

**Closed by inlet** 2018-01-05 09:08 UTC
